apiVersion: v1
kind: Pod
metadata:
    name: namespace-demo-pod
spec:
    containers:
        - name: web-app
          image: configmap-namespaces:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config