apiVersion: v1
kind: Pod
metadata:
  name: s3-flow-pod
spec:
  volumes:
  - name: content-volumes
    emptyDir: {}
  - name: ssh-key-vol
    secret:
      secretName: ssh-key-secret

  initContainers:
  - name: fetcher
    image: alpine:latest
    # SCP Command Fix:
    # 1. Prepare Key
    # 2. SSH to remote server and CREATE the file (since it's missing)
    # 3. SCP the file back
    command: 
      - "sh"
      - "-c"
      - |
        apk add --no-cache openssh-client && \
        cp /etc/ssh-key/ssh-privatekey /tmp/id_rsa && \
        chmod 400 /tmp/id_rsa && \
        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa azureuser@172.208.48.169 "echo '<h1>Hello from Azure VM! Created by K8s.</h1>' > index.html" && \
        scp -o StrictHostKeyChecking=no -i /tmp/id_rsa azureuser@172.208.48.169:index.html /data/index.html
    volumeMounts:
    - name: content-volumes
      mountPath: /data
    - name: ssh-key-vol
      mountPath: /etc/ssh-key
      readOnly: true

  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: content-volumes
      mountPath: /usr/share/nginx/html