apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: justice-demo
  namespace: openshift-gitops
patches:
spec:
  project: default
  source:
    repoURL: https://github.com/gaip/devops-exercises.git
    targetRevision: justitia
    path: justitia-demo/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hasan-turhal-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true