apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: justice-demo
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hasan-turhal-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true