apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
  - name: web-app
    image: configmap-demo:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 5000
    envFrom:
    - configMapRef:
        name: app-config-prod